// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llupygqywdrdoempourj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsdXB5Z3F5d2RyZG9lbXBvdXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMjQxMjUsImV4cCI6MjA1MTcwMDEyNX0.4nuLy4pjGv3AOOUJS-doUUw_1SVTOzdlJ0ochJFJQ4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);